# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
QT += widgets network sql
QT += svg

TARGET = MMOffline
DESTDIR = ../Win32/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += .
win32:RC_FILE = MMOffline.rc
TRANSLATIONS += translations/mmoffline_en.ts \
    translations/mmoffline_ro.ts \
    translations/mmoffline_ru.ts
HEADERS += ./MMOffline.h \
    ./Widgets/parents/abstractNodeInterface.h \
    ./Widgets/parents/inframedWidget.h \
    ./Widgets/ElementWidgets/MegaIconButton.h \
    ./Widgets/ElementWidgets/BigButtonsSpinbox.h \
    ./Widgets/ModeDefining/OnlineLoginWidget.h \
    ./Widgets/ModeDefining/StartingScreen.h \
    ./Widgets/ModeDefining/SettingsScreen.h \
    ./Widgets/ModeDefining/AssertionLabel.h \
    ./Widgets/MultibranchWidgets/GroupSelectionWidget.h \
    ./Widgets/MultibranchWidgets/ProductSelectionWidget.h \
    ./Widgets/MultibranchWidgets/DocumentSelectionWidget.h \
    ./Widgets/MultibranchWidgets/ProductSelectionBranch.h \
    ./Widgets/LogBranch/DocumentEntrySelectionSubbranch.h \
    ./Widgets/LogBranch/LogBranchRoot.h \
    ./Widgets/Syncing/SyncMenuWidget.h \
    ./Widgets/Syncing/SyncInfoWidget.h \
    ./Widgets/DocumentBranch/DocumentRootWidget.h \
    ./Widgets/DocumentBranch/ClientSelectionWidget.h \
    ./Widgets/DocumentBranch/DocumentCreationScreen.h \
    ./Widgets/DocumentBranch/EntryCreationScreen.h \
    ./Widgets/ExtendedDelegates/DelegateUtility.h \
    ./Widgets/ExtendedDelegates/ClientsDelegate.h \
    ./Widgets/ExtendedDelegates/ProductsDelegate.h \
    ./Widgets/ExtendedDelegates/GroupDelegate.h \
    ./Widgets/ExtendedDelegates/DocumentsDelegate.h \
    ./Widgets/ExtendedDelegates/EntryDelegate.h \
    ./Networking/queryTemplates.h \
    ./Networking/RequestAwaiter.h \
    ./Networking/dataupdateengine-http.h \
    ./Networking/Parsers/abs_parser.h \
    ./Networking/Parsers/ErrorParser.h \
    ./Networking/Parsers/JsonUniresult.h \
    ./Networking/Parsers/RequestParser.h \
    ./Networking/Parsers/LinearParser.h \
    ./debugtrace.h \
    ./Widgets/utils/ElementsStyles.h \
    ./Widgets/utils/GlobalAppSettings.h \
    ./Widgets/utils/EventsAndFilters.h \
    ./Dataprovider/IdGenerator.h \
    ./Dataprovider/SqliteDataProvider.h \
    ./Dataprovider/TableHandlers.h \
    ./Dataprovider/FileParser.h \
    ./Dataprovider/Entities/abs_entity.h \
    ./Dataprovider/Entities/DocumentEntity.h \
    ./Dataprovider/Entities/DocumentEntryEntity.h \
    ./Dataprovider/Entities/FieldTablesPredefines.h \
    ./Dataprovider/Entities/NamedIdEntity.h \
    ./Dataprovider/Entities/ProductEntity.h \
    ./Dataprovider/DataEntities.h \
    ./Dataprovider/Entities/ClientEntity.h \
    ./Dataprovider/Entities/GroupEntity.h \
    Widgets/ElementWidgets/CardMenuButton.h \
    Widgets/ElementWidgets/FooterButton.h \
    Widgets/ElementWidgets/Modernamountstepper.h \
    Widgets/ElementWidgets/OutlineActionButton.h \
    Widgets/ElementWidgets/StatusDialog.h \
    Widgets/ExtendedDelegates/ModernDocumentsDelegate.h \
    Widgets/utils/ElidedComboBox.h \
    Widgets/utils/ModernDatePickerDialog.h \
    Widgets/utils/ModernSelectionDialog.h \
    Widgets/utils/SvgHelper.h
SOURCES += ./main.cpp \
    ./MMOffline.cpp \
    ./Widgets/ElementWidgets/BigButtonsSpinbox.cpp \
    ./Widgets/ElementWidgets/MegaIconButton.cpp \
    ./Widgets/parents/abstractNodeInterface.cpp \
    ./Widgets/parents/inframedWidget.cpp \
    ./Widgets/ModeDefining/OnlineLoginWidget.cpp \
    ./Widgets/ModeDefining/SettingsScreen.cpp \
    ./Widgets/ModeDefining/StartingScreen.cpp \
    ./Widgets/LogBranch/LogBranchRoot.cpp \
    ./Widgets/ModeDefining/AssertionLabel.cpp \
    ./Widgets/MultibranchWidgets/DocumentSelectionWidget.cpp \
    ./Widgets/DocumentBranch/ClientSelectionWidget.cpp \
    ./Widgets/LogBranch/DocumentEntrySelectionSubbranch.cpp \
    ./Widgets/MultibranchWidgets/GroupSelectionWidget.cpp \
    ./Widgets/MultibranchWidgets/ProductSelectionBranch.cpp \
    ./Widgets/MultibranchWidgets/ProductSelectionWidget.cpp \
    ./Widgets/Syncing/SyncInfoWidget.cpp \
    ./Widgets/Syncing/SyncMenuWidget.cpp \
    ./Widgets/ExtendedDelegates/ClientsDelegate.cpp \
    ./Widgets/ExtendedDelegates/DelegateUtility.cpp \
    ./Widgets/ExtendedDelegates/DocumentsDelegate.cpp \
    ./Widgets/ExtendedDelegates/EntryDelegate.cpp \
    ./Widgets/ExtendedDelegates/GroupDelegate.cpp \
    ./Widgets/ExtendedDelegates/ProductsDelegate.cpp \
    ./Widgets/DocumentBranch/DocumentCreationScreen.cpp \
    ./Widgets/DocumentBranch/DocumentRootWidget.cpp \
    ./Widgets/DocumentBranch/EntryCreationScreen.cpp \
    ./Networking/dataupdateengine-http.cpp \
    ./Networking/Parsers/JsonUniresult.cpp \
    ./Networking/queryTemplates.cpp \
    ./Networking/RequestAwaiter.cpp \
    ./Networking/Parsers/abs_parser.cpp \
    ./Networking/Parsers/ErrorParser.cpp \
    ./Networking/Parsers/LinearParser.cpp \
    ./Networking/Parsers/RequestParser.cpp \
    ./debugtrace.cpp \
    ./Widgets/utils/ElementsStyles.cpp \
    ./Widgets/utils/EventsAndFilters.cpp \
    ./Widgets/utils/GlobalAppSettings.cpp \
    ./Dataprovider/FileParser.cpp \
    ./Dataprovider/IdGenerator.cpp \
    ./Dataprovider/SqliteDataProvider.cpp \
    ./Dataprovider/TableHandlers.cpp \
    ./Dataprovider/DataEntities.cpp \
    ./Dataprovider/Entities/abs_entity.cpp \
    ./Dataprovider/Entities/ClientEntity.cpp \
    ./Dataprovider/Entities/DocumentEntity.cpp \
    ./Dataprovider/Entities/DocumentEntryEntity.cpp \
    ./Dataprovider/Entities/FieldTablesPredefines.cpp \
    ./Dataprovider/Entities/GroupEntity.cpp \
    ./Dataprovider/Entities/NamedIdEntity.cpp \
    ./Dataprovider/Entities/ProductEntity.cpp \
    Widgets/ElementWidgets/CardMenuButton.cpp \
    Widgets/ElementWidgets/FooterButton.cpp \
    Widgets/ElementWidgets/Modernamountstepper.cpp \
    Widgets/ElementWidgets/OutlineActionButton.cpp \
    Widgets/ElementWidgets/StatusDialog.cpp \
    Widgets/ExtendedDelegates/ModernDocumentsDelegate.cpp \
    Widgets/utils/ModernDatePickerDialog.cpp \
    Widgets/utils/ModernSelectionDialog.cpp
RESOURCES += MMOffline.qrc

DISTFILES += \
    android/AndroidManifest.xml \
    android/build.gradle \
    android/res/values/libs.xml \
    res/settings1.png

android {
    ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android
    QT += androidextras
}

